services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - DATABASE_URL=${SQLALCHEMY_DATABASE_URI}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: