"""Add Highlight table

Revision ID: 53ee4e6399b6
Revises: 03fc186b4b9f
Create Date: 2025-05-21 19:19:01.688270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ee4e6399b6'
down_revision = '03fc186b4b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('context', sa.String(length=500), nullable=True),
    sa.Column('page_title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlights')
    # ### end Alembic commands ###
